The $line->{'name'} backslash quoting here is quite incomprehensible and looks to me like it may be duplicated unnecessarily.  In any case, the key thing is to make sure that there are an odd number of backslashes before single quotes, so that you don't get mail from cron saying that:
Output method failure of postgres:////antura.health_report failed with
Cannot execute >insert......
ERROR: Can\\'t get VID data!\\
....

because a quote preceded by two backslashes is unescaped, and causes problems.